"""
One-page PDF health report (ReportLab).
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.platypus.flowables import HRFlowable

from model.train import FEATURE_COLS
from utils.health_thresholds import get_badge

_RISK_LABEL_HEX_HTML = {
    "Low": "#2ecc71",
    "Moderate": "#f39c12",
    "High": "#e74c3c",
}

_RECOMMENDATIONS = [
    "Maintain fasting glucose below 100 mg/dL through diet and exercise",
    "A BMI between 18.5–24.9 significantly reduces diabetes risk",
    "150 minutes of moderate exercise per week improves insulin sensitivity",
    "Regular HbA1c screening is recommended if glucose is borderline or high",
    "Consult your physician before making significant lifestyle changes",
]

_PLACEHOLDER_AI = (
    "Run the AI Explanation in the app for personalized insights."
)


def _format_metric_value(feature: str, value: float) -> str:
    if feature in ("Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "Age"):
        return str(int(round(float(value))))
    if feature == "BMI":
        return f"{float(value):.1f}"
    if feature == "DiabetesPedigreeFunction":
        return f"{float(value):.3f}"
    return str(value)


def _shap_to_image_flowable(shap_fig: Any, max_width: float = 6.5 * inch) -> Any | None:
    if shap_fig is None:
        return None
    try:
        png_bytes = shap_fig.to_image(format="png", width=720, height=420, scale=1)
    except Exception:
        return None
    bio = io.BytesIO(png_bytes)
    from reportlab.platypus import Image

    aspect = 420 / 720
    w = float(max_width)
    h = w * aspect
    return Image(bio, width=w, height=h)


def generate_pdf_report(
    user_inputs: dict[str, float],
    risk_score: float,
    risk_label: str,
    shap_fig: Any,
    percentiles: dict[str, int] | None,
    llm_explanation: str | None,
) -> io.BytesIO:
    """
    Build a one-page PDF and return a BytesIO buffer (caller should not rely on disk).
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.65 * inch,
        leftMargin=0.65 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.55 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        name="ReportTitle",
        parent=styles["Heading1"],
        fontSize=20,
        leading=24,
        alignment=TA_CENTER,
        spaceAfter=6,
        textColor=colors.HexColor("#1a1a2e"),
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        name="ReportSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#555555"),
        spaceAfter=12,
    )
    h2_style = ParagraphStyle(
        name="H2",
        parent=styles["Heading2"],
        fontSize=12,
        leading=15,
        spaceBefore=14,
        spaceAfter=8,
        textColor=colors.HexColor("#1a1a2e"),
        fontName="Helvetica-Bold",
    )
    body = ParagraphStyle(
        name="Body",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        alignment=TA_LEFT,
    )
    body_center = ParagraphStyle(
        name="BodyCenter",
        parent=body,
        alignment=TA_CENTER,
    )
    risk_big = ParagraphStyle(
        name="RiskBig",
        parent=styles["Normal"],
        fontSize=16,
        leading=20,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        spaceAfter=6,
    )
    risk_score_style = ParagraphStyle(
        name="RiskScore",
        parent=styles["Normal"],
        fontSize=12,
        leading=16,
        alignment=TA_CENTER,
        spaceAfter=10,
    )
    explain_style = ParagraphStyle(
        name="Explain",
        parent=styles["Normal"],
        fontSize=9,
        leading=13,
        alignment=TA_JUSTIFY,
    )
    footer_style = ParagraphStyle(
        name="Footer",
        parent=styles["Normal"],
        fontSize=7,
        leading=10,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#666666"),
        fontName="Helvetica-Oblique",
        spaceBefore=16,
    )

    story: list[Any] = []
    story.append(Paragraph("Personal Health Risk Report", title_style))

    today = datetime.now().strftime("%B %d, %Y")
    story.append(
        Paragraph(
            f"Generated by Health Risk Explorer · {today}",
            subtitle_style,
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))

    # Section 1 — Risk Summary
    story.append(Spacer(1, 8))
    hx = _RISK_LABEL_HEX_HTML.get(risk_label, "#333333")
    risk_title_html = f'<font color="{hx}">{risk_label} Diabetes Risk</font>'
    story.append(Paragraph(risk_title_html, risk_big))
    story.append(
        Paragraph(f"Risk Score: {risk_score * 100:.0f}%", risk_score_style),
    )

    # Optional SHAP figure (function parameter; fits between summary and metrics)
    shap_flow = _shap_to_image_flowable(shap_fig)
    if shap_flow is not None:
        story.append(Paragraph("<b>SHAP overview (model contributions)</b>", h2_style))
        story.append(shap_flow)
        story.append(Spacer(1, 8))

    # Section 2 — Health metrics table
    story.append(Paragraph("Your Health Metrics", h2_style))
    table_data = [["Feature", "Your Value", "Clinical Status"]]
    for feat in FEATURE_COLS:
        val = float(user_inputs[feat])
        _, clinical, _ = get_badge(feat, val)
        table_data.append([feat, _format_metric_value(feat, val), clinical])

    t = Table(table_data, colWidths=[2.2 * inch, 1.4 * inch, 1.5 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8e8e8")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ALIGN", (1, 0), (1, -1), "CENTER"),
                ("ALIGN", (2, 0), (2, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.append(t)

    # Section 3 — Population
    story.append(Paragraph("Population Comparison", h2_style))
    pct_map = percentiles or {}
    notable = [(f, p) for f, p in sorted(pct_map.items()) if p > 60]
    if not notable:
        story.append(Paragraph("No metrics above the 60th population percentile.", body))
    else:
        for feat, p in notable:
            story.append(
                Paragraph(
                    f"Your {feat} is higher than {p}% of the population.",
                    body,
                )
            )

    # Section 4 — AI explanation
    story.append(Paragraph("What This Means For You", h2_style))
    ai_text = (llm_explanation or "").strip()
    if not ai_text:
        ai_text = _PLACEHOLDER_AI
    escaped = (
        ai_text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    story.append(Paragraph(escaped.replace("\n", "<br/>"), explain_style))

    # Section 5 — Recommendations
    story.append(Paragraph("General Recommendations", h2_style))
    bullets = "<br/>".join(f"• {item}" for item in _RECOMMENDATIONS)
    story.append(Paragraph(bullets, body))

    # Footer
    story.append(
        Paragraph(
            "⚠️ This report is for informational purposes only and does not constitute "
            "medical advice. Always consult a qualified healthcare professional.",
            footer_style,
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer
